version: '3.0'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    ports:
      - 5601:5601
    links:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    command: bash -c "bin/logstash-plugin install logstash-input-file && logstash -f /logstash/logstash_cied10.conf"
    links:
      - elasticsearch
    volumes:
      - ./:/logstash
